services:
  beskid:
    build:
      context: ../..
      dockerfile: beskid_distrib/docker/Dockerfile
      args:
        BESKID_VERSION: latest
    image: beskid:local
    entrypoint: ["beskid"]
    command: ["--version"]
    volumes:
      - ../..:/workspace
    working_dir: /workspace

  beskid-runner:
    build:
      context: ../..
      dockerfile: beskid_distrib/docker/Dockerfile.runner
      args:
        BESKID_VERSION: latest
    image: beskid-runner:local
    entrypoint: ["beskid"]
    command: ["--version"]
    volumes:
      - ../..:/workspace
    working_dir: /workspace
